# Setup - variables available at site.data.meta.title, site.data.meta.tagline, etc.
title:            'Culture Ship Randomizer'
tagline:          'A gravitas free zone.'
description:      'Quick & Easy online tool for generating culture ship names'
author:
  name:           'Bryan Schuetz'
  url:            http://distressignal.com
github:
  repo:
version:          0.1
